version: 2
updates:
# Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
# Update Packages
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
