name: Generate Contributors List
on:
  push:
    branches:
      - main
jobs:
  generate-contributors-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate contributors list
        uses: peter-evans/contributors-generator@v2.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          include-merge-commits: false
      - name: Commit contributors list
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CONTRIBUTORS.md
          git commit -m "Updated contributors list"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: "."
