name: dependencies

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Run once a day

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dependabot
        uses: dependabot/dependabot-core@0.215.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: '/'
