name: Welcome Message

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Send welcome message
        uses: actions/github-script@v4
        with:
          script: |
            const issueOrPullRequest = context.payload.issue || context.payload.pull_request;
            const author = issueOrPullRequest.user.login;
            const message = `Welcome, @${author}! Thanks for opening this ${issueOrPullRequest.pull_request ? 'pull request' : 'issue'}!`;

            return github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueOrPullRequest.number,
              body: message
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
