name: Upgrade Packages
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  upgrade-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Yarn
        run: npm install -g yarn
      - name: Upgrade Packages
        run: yarn upgrade
