name: Update and publish package
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn install --latest

    - name: Check for updates
      run: |
        yarn outdated

    - name: Build package
      run: |
        yarn build

    - name: Publish package
      run: |
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
