name: Semver Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Determine version bump
        id: determine_version
        run: |
          CURRENT_VERSION=$(git tag --sort=-v:refname | head -1)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{printf "%d.%d.%d", $1, $2+1, $3}')
          echo ::set-output name=bump::$NEW_VERSION
      - name: Get list of fixed issues
        id: get_fixed_issues
        run: |
          FIXED_ISSUES=$(git log --oneline $CURRENT_VERSION..HEAD | grep -E '^(fix|feat|chore|docs):' | sed -E 's/^(fix|feat|chore|docs):\s*(.*)/\* \2/')
          if [[ -z $FIXED_ISSUES ]]; then
            echo ::set-output name=issues::"No fixed issues."
          else
            echo ::set-output name=issues::$FIXED_ISSUES
          fi
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ steps.determine_version.outputs.bump }}
          release_name: Release ${{ steps.determine_version.outputs.bump }}
          body: |
            Changes in this release:
            ${{ steps.get_fixed_issues.outputs.issues }}
          draft: false
          prerelease: false
